spring:
  application:
    name: ludotheque
  data:
    mongodb:
      #username: sa
      #password: Passw0rd
      #host: localhost
      #port: 27017
      database: LUDO_DB
      uri: mongodb+srv://zawarudo:zawarudo@cluster0.4bgfpg7.mongodb.net/?appName=Cluster0
      #authentication-database: admin
      auto-index-creation: true
