spring:
  application:
    name: ludotheque
  data:
    mongodb:
      #username: sa
      #password: Passw0rd
      #host: localhost
      #port: 27017
      database: LUDO_DB
      uri: mongodb://user:pass@192.168.50.128:27017
      #authentication-database: admin
      auto-index-creation: true
