spring:
  application:
    name: ludotheque
  data:
    mongodb:
      username: sa
      password: Passw0rd
      host: localhost
      port: 27017
      database: LUDO_DB
      authentication-database: admin
